import React from "react"

export const metadata = {
  title: 'Practice',
  description: 'Generated by Next.js',
}

type RootLayoutProps = {
  children: React.ReactNode
}
export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
